SFTP:
  host: "51.91.127.144"
  port: 2225
  username: "sftp username"
  private_key_file: "/path/to/private/ssh/keyfile"
  private_key_password: "password for ssh keyfile"
  known_hosts_file: "/path/to/server/public/key(known_hosts)"
  sftp_directory: "directory where events are stored in sftp"
  local_directory: "directory where events will be stored locally"

MISP:
  url: "your misp instance url"
  key: "your misp instance api key"
  ssl: true #Use https requests instead of http
  CA_BUNDLE: "your misp certificate bundle"

MISC:
  logging_conf: conf/logging.yaml
  logging_file: log/sftp.log
