SFTP:
  #Ne pas modifier
  host: "51.91.127.144"
  #Ne pas modifier
  port: 2225
  #Ne pas modifier
  sftp_directory: "/data/MS/misp_events"

  username: "sftp username"
  private_key_file: "/path/to/private/ssh/keyfile"
  #Laisser vide ("") pour spécifier le mot de passe a l'execution du script
  private_key_password: "password for ssh keyfile"
  known_hosts_file: "/path/to/server/public/key(known_hosts)"
  local_directory: "./output"

MISP:
  url: "url instance misp"
  key: "instance misp api key"
  ssl: true #Use https requests instead of http
  CA_BUNDLE: "bundle de certificats pour la communication https avec misp (si ssl == true)"

MISC:
  logging_conf: conf/logging.yaml
  logging_file: log/sftp.log
