LOGGING:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s - %(levelname)s - %(name)s.%(funcName)s(): %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: "log/sftp.log"
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
  loggers:
    sampleLogger:
      level: DEBUG
      handlers:
        - file
        - console
      propagate: "no"
  root:
    level: DEBUG
    handlers:
      - console
      - file
